language: ruby
rvm: 2.1.5
script: bin/rake spec
deploy:
  provider: heroku
  api_key:
    secure: Cc0AciSWNyCDmUEHV/uxzIbo7mSVH0bDIQf9zTa+etlMUobyb1SqIxXPKYqd8ByZRRzbbeUIRMxRakZapuALtW2Uyh7pZDrUNfpOPxdzq50c9zqhy/NdLC+Z/RdmXUfNvvy6fHK4ZE9Co8Ox9IcUpSyoUmjXfTauPvACJfKWzc8=
  app: turi
  run:
    - "rake db:migrate RAILS_ENV=production"
    - restart
  on:
    repo: turi-inc/turi
    branch: master